[package]
name = "od-nat-piercer"
version = "0.1.0"
edition = "2024"

[dependencies]
local-ip-address = "0.6.5"
tokio = { version = "1", features = ["full"]}
warp = "0.3"
reqwest = { version = "0.11", features = ["blocking"] }
