[package]
name = "od-nat-piercer"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
rand = "0.8"
tokio-tungstenite = "0.23"
futures-util = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
openssl = { version = "0.10.76", features = ["vendored"] }

[lints.clippy]
pedantic = "warn"
