services:
  od-nat-piercer:
    image: "${OD_NAT_PIERCER_IMAGE:?OD_NAT_PIERCER_IMAGE must be set}"
    pull_policy: always
    ports: 
      - "0.0.0.0:2131:2131"
      - "0.0.0.0:2131:2131/udp"
      - "0.0.0.0:2132:2132"
      - "0.0.0.0:2132:2132/udp"
      - "0.0.0.0:2133:2133"
