name: Rust CI

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Clippy 
      run: cargo clippy --release -- -D warnings -A clippy::too-many-arguments -A clippy::for-kv-map
    - name: Run tests
      run: cargo test --verbose

